apps/blog/urls.py
from django.urls import path
from blog import views
from django.contrib.auth.views import LogoutView

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('submit', views.submit, name='submit'),
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', LogoutView.as_view(next_page='/'), name='logout'),
    path('post', views.post_detail, name='post'),
    path('like_post', views.like_post, name='like_post'),
    path('comment_post', views.comment_post, name='comment_post'),
    path('delete_comment', views.delete_comment, name='delete_comment'),
    path('delete_post', views.delete_post, name='delete_post'),
    path('profile', views.profile, name='profile'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
    path('about', views.about, name='about'),
    path('<str:undefined_url>', views.index, name='undefined_url'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('blog.urls', 'blog')),
    path('admin/', admin.site.urls),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission
import uuid

def upload_to(instance, filename):
    return f'blog/{instance.author.username}/{filename}'

class BlogUser(AbstractUser):
    groups = models.ManyToManyField(Group, related_name='blog_users', blank=True)
    user_permissions = models.ManyToManyField(Permission, related_name='blog_users', blank=True)
    avatar = models.ImageField(upload_to="avatars", blank=True, null=True)
    

class Post(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=200)
    content = models.TextField()
    publish_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(BlogUser, on_delete=models.CASCADE)
    votes = models.IntegerField(default=0)
    image = models.ImageField(upload_to=upload_to, null=True)

    def __str__(self):
        return self.title
    
class BlogGroup(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(BlogUser, on_delete=models.CASCADE, related_name='created_groups')
    posts = models.ManyToManyField(Post)
    members = models.ManyToManyField(BlogUser, related_name='joined_groups')
    
    def __str__(self):
        return self.title

class Comment(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    content = models.TextField()
    publish_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(BlogUser, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.content

class Vote(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(BlogUser, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, blank=True, null=True)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return f"{self.user} voto por {self.post}"

class Tag(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=50)
    posts = models.ManyToManyField(Post)

    def __str__(self):
        return self.name

apps/blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user
from blog.models import BlogUser, Post

class RegisterBlogUserForm(UserCreationForm):
    first_name = forms.CharField(max_length=100, required=True)
    last_name = forms.CharField(max_length=100, required=True)
    email = forms.EmailField(required=True)
    confirmEmail = forms.EmailField(label='Confirmar correo electrónico', required=True)
    avatar = forms.ImageField(required=False)
    
    class Meta:
        model = BlogUser
        fields = ['first_name', 'last_name', 'username', 'email', 'confirmEmail', 'password1', 'password2', 'avatar']
        
class PostForm(forms.ModelForm):
    title = forms.CharField(max_length=300, required=True)
    content = forms.CharField(max_length=1000, required=True)
    image = forms.ImageField(required=False)
    author = forms.Field(required=False)
    
    class Meta:
        model = Post
        fields = ['title', 'content', 'author', 'image']
        
class CommentForm(forms.Form):
    content = forms.CharField(max_length=1000, required=True)
    post = forms.CharField(required=True)

apps/blog/controllers/user_controller.py
from django.contrib.auth import authenticate, login as auth_login
from django.contrib.auth.forms import AuthenticationForm
from blog.forms import RegisterBlogUserForm

def check_user_login(request):
    try:
        form = AuthenticationForm(request.POST, data = request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                auth_login(request, user)
                return True
            else: 
                return False
    except Exception as e:
        raise Exception(f'Error al validar el formulario [{ e }]')
    
def register_user(request):
    try:
        if request.method == 'POST':
            form = RegisterBlogUserForm(request.POST)
            if form.is_valid():
                user = form.save()
                auth_login(request, user)
    except:
        raise Exception(f'')

apps/blog/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from .controllers.user_controller import auth_login
from .forms import RegisterBlogUserForm, PostForm, CommentForm
from . import models
from django.contrib.auth.decorators import login_required

# Create your views here.
app_name = 'blog'

def index(request, message = None, undefined_url=None):
    if undefined_url is not None:
        return redirect('blog:index')
    search = request.GET.get('search')
    if search:
        post_list = models.Post.objects.filter(Q(title__icontains=search) | Q(content__icontains=search)).order_by('-publish_date')
    else:
        post_list = models.Post.objects.all().order_by('-publish_date')
    for post in post_list:
        post.commets = models.Comment.objects.filter(post=post).count()
        post.votes = models.Vote.objects.filter(post=post).count()
        if request.user.is_authenticated:
            vote = models.Vote.objects.filter(post=post, user=request.user)
            if vote:
                post.vote = True
    return render(request, 'blog/index.html', { 'post_list': post_list, 'message': message })

def submit(request):
    user = request.user
    if not user.is_authenticated:
        return redirect('blog:register')
    elif request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            print(post)
            return redirect('blog:index')
        errores = []
        for field, error_msgs in form.errors.items():
            for error_msg in error_msgs:
                errores.append(f"{error_msg}")
        return render(request, 'blog/register.html', { 'error': errores, 'form': form.data })
    return render(request, 'blog/submit.html')


# Register:::


def register(request):
    if request.method == 'GET':
        return render(request, 'blog/register.html')
    elif request.method == 'POST':
        form = RegisterBlogUserForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('blog:index') 
        errores = []
        for field, error_msgs in form.errors.items():
            for error_msg in error_msgs:
                errores.append(f"{error_msg}")
        return render(request, 'blog/register.html', { 'error': errores, 'form': form.data })
    else:
        return render(request, 'blog/register.html')

# Login:::
from .controllers.user_controller import check_user_login

def login(request):
    if request.method == 'POST':
        try:
            if check_user_login(request):
                return redirect('blog:index')
            else:
                return render(request, 'blog/register.html', { 
                    'status': 'error', 
                    'message': 'Usuario ingresado no se encuentra registrado\n Intentalo nuevamente, de lo contrario, registrate! 👀' 
                })
        except Exception as ex:
            return redirect('blog:index')
    else:
        return redirect('blog:index')
    
@login_required
def profile(request):
    try:
        votes = models.Vote.objects.filter(user=request.user).count()
        posts = models.Post.objects.filter(author=request.user).count()
    except Exception as e:
        print(e)
    return render(request, 'blog/profile.html', { 'post_count': posts, 'likes_count': votes })

@login_required
def edit_profile(request):
    if request.method == 'POST':
        avatar = request.FILES.get('avatar')
        user = request.user
        user.first_name = request.POST['first_name']
        user.last_name = request.POST['last_name']
        user.email = request.POST['email']
        if avatar:
            user.avatar = avatar
        user.save()
        return redirect('blog:profile')
    return render(request, 'blog/edit_profile.html')
    
def post_detail(request):
    try:
        id = request.GET.get('id')
        post = models.Post.objects.get(id=id)
        if post:
            comments = models.Comment.objects.filter(post = post)
            post.commets = models.Comment.objects.filter(post=post).count()
            post.votes = models.Vote.objects.filter(post=post)
            if request.user.is_authenticated:
                vote = models.Vote.objects.filter(post=post, user=request.user)
                if vote:
                    post.vote = True
            return render(request, 'blog/post_detail.html', { 'post': post, 'comments': comments })
        else:
            return redirect('blog:index')
    except Exception as e:
        print(e)
        return redirect('blog:index')
    
def like_post(request):
    referer = request.META.get('HTTP_REFERER')
    try:
        if request.user.is_authenticated:
            id = request.GET.get('id')
            post = models.Post.objects.filter(id = id).first()
            vote_verification = models.Vote.objects.filter(post = post, user = request.user).first()
            if vote_verification is None:
                vote = models.Vote(user=request.user, post=post)
                vote.save()
            else:
                vote_verification.delete()
            return redirect(referer)
        else:
            return redirect('blog:register')
    except Exception as e:
        print(e)
        return redirect('blog:index')
    
def comment_post(request):
    referer = request.META.get('HTTP_REFERER')
    try:
        if request.user.is_authenticated and request.method == "POST":
            form = CommentForm(request.POST)
            if form.is_valid():
                form_info = form.cleaned_data
                post = models.Post.objects.filter(id=form_info['post']).first()
                comment = models.Comment(content=form_info['content'], author=request.user, post=post)
                comment.save()
        else:
            return redirect('blog:register')
    except Exception as e:
        print(e)
    return redirect(referer)

def delete_comment(request):
    referer = request.META.get('HTTP_REFERER')
    try:
        id = request.GET.get('id')
        comment = models.Comment.objects.get(id = id)
        if request.user.is_authenticated and comment:
            comment.delete()
    except Exception as e:
        print(e)
    return redirect(referer)

def delete_post(request):
    try:
        id = request.GET.get('id')
        post = models.Post.objects.get(id = id)
        if request.user.is_authenticated and post and post.author == request.user:
            post.delete()
            return index(request, { 'success': 'Publicación eliminada con exito!' })
        else:
            return index(request, { 'error': 'No cumple con las condiciones para poder eliminar esta publicación!' })
    except Exception as e:
        print(e)
        return index(request, { 'error': 'Ocurrio un error al intentar eliminar la publicación!' })
    
def about(request):
    return render(request, 'blog/about.html')

apps/blog/templates/blog/about.html
{% extends 'base_blog.html' %}
{% load static %}
{% block PAGE_TITLE %} Profile {% endblock PAGE_TITLE %}
{% block PAGE_CONTENT %}
<section class="container mt-5 col-md-10 text-white w-100 font-monospace" style="padding-left: 30%; padding-top: 60px;">
    <h1 class="text-warning">Sobre mí</h1>
    <div class="mt-3 d-flex">
        <div class="d-flex flex-column w-75">
            <div class="d-flex">
                <p class="text-white fs-5 w-100">
                    Mi nombre es José Candia, un ingeniero en informática con experiencia en tecnología y transporte. </br>
                    Mi pasión es desarrollar soluciones tecnológicas innovadoras que mejoren los procesos empresariales. </br>
                    Soy proactivo, comprometido y apasionado por aprender y colaborar en equipos multidisciplinarios.
                </p>
                <div class="d-flex flex-column ms-5">
                    <a class="text-warning mb-3" href="https://www.linkedin.com/in/jcandiap/" target="_blank">LinkedIn</a>
                    <a class="text-warning" href="https://github.com/jcandiap" target="_blank">GitHub</a>
                </div>
            </div>
            <h3 class="text-warning">Experiencias profesionales</h3>
            <div class="d-flex flex-column">
                <div class="d-flex flex-column">
                    <span class="mt-3 text-warning text-bold">Desarrollador Fullstack (diciembre 2019 - actual)</span>
                    <small>Pullman Bus S.A.</small>
                </div>
                <div class="d-flex flex-column">
                    <span class="mt-3 text-warning text-bold">Práctica Analista programador computacional (diciembre 2018 - febrero 2019)</span>
                    <small>Pullman Bus S.A.</small>
                </div>
                <div class="d-flex flex-column">
                    <span class="mt-3 text-warning text-bold">Analista Contable (marzo 2014 - febrero 2015)</span>
                    <small>Pullman Bus S.A.</small>
                </div>
            </div>
        </div>
    </div>
    <div class="mt-5 d-flex flex-column w-75">
        <h1 class="text-warning">Conocimientos técnicos</h1>
        <h3 class="mt-3 mx-auto">Lenguajes de programación</h3>
        <div class="mt-4 d-flex justify-content-evenly flex-wrap mx-auto w-100">
            <img src="{% static 'images/java.png' %}" width="100" height="100" />
            <img src="{% static 'images/javascript.png' %}" width="100" height="100" />
            <img src="{% static 'images/python.png' %}" width="100" height="100" />
            <img src="{% static 'images/csharp.png' %}" width="100" height="100" />
            <img src="{% static 'images/php.png' %}" width="100" height="100" />
            <img src="{% static 'images/dart.png' %}" width="100" height="100" />
        </div>
        <h3 class="mt-4 mx-auto">Tecnologías / Frameworks</h3>
        <div class="mt-4 d-flex justify-content-evenly flex-wrap mx-auto w-100">
            <img src="{% static 'images/angular.png' %}" width="100" height="100" />
            <img src="{% static 'images/react.png' %}" width="100" height="100" />
            <img src="{% static 'images/vue.png' %}" width="100" height="100" />
            <img src="{% static 'images/nestjs.png' %}" width="100" height="100" />
            <img src="{% static 'images/ionic.png' %}" width="100" height="100" />
            <img src="{% static 'images/nextjs.png' %}" width="100" height="100" />
            <img src="{% static 'images/flutter.png' %}" width="100" height="100" />
            <img src="{% static 'images/html.png' %}" width="100" height="100" />
            <img src="{% static 'images/css.png' %}" width="100" height="100" />
        </div>
        <h3 class="mt-4 mx-auto">Herramientas</h3>
        <div class="mt-4 d-flex justify-content-evenly flex-wrap mx-auto w-100">
            <img src="{% static 'images/gitlab.png' %}" width="100" height="100" />
            <img src="{% static 'images/jenkins.png' %}" width="100" height="100" />
            <img src="{% static 'images/jira.png' %}" width="100" height="100" />
            <img src="{% static 'images/office.png' %}" width="100" height="100" />
            <img src="{% static 'images/trello.png' %}" width="100" height="100" />
            <img src="{% static 'images/github.png' %}" width="100" height="100" />
        </div>
    </div>
</section>
{% endblock PAGE_CONTENT %}

apps/blog/templates/blog/edit_profile.html
{% extends 'base_blog.html' %}
{% load static %}
{% block PAGE_TITLE %} Profile {% endblock PAGE_TITLE %}
{% block PAGE_CONTENT %}
<section class="container mt-5 col-md-10 text-white w-100" style="padding-left: 30%; padding-top: 60px;">
    <div class="card w-75 d-flex flex-column ps-3 pe-3 bg-dark pt-3 pb-3 mt-4">
        <h3>Edición del perfil</h3>
        <form class="d-flex" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mt-5 ms-3">
                <img 
                    src="{% if user.avatar %} {{ user.avatar.url }} {% else %} {% static 'base_profile.png' %} {% endif %}" 
                    alt="" 
                    id="user-avatar"
                    width="250" 
                    height="250" 
                    class="rounded-circle">
                <div class="input-group my-3">
                    <input type="file" name="avatar" accept="image/*" class="form-control" id="inputFile">
                </div>
            </div>
            <div class="d-flex flex-column w-100 ps-5">
                <div class="form-floating mb-3">
                    <input type="text" class="form-control bg-dark text-white" id="username" name="username" readonly placeholder="Nombre de usuario" value="{{ user.username }}">
                    <label for="username" class="text-warning">Nombre de usuario:</label>
                </div>
                <div class="form-floating mb-3">
                    <input type="text" class="form-control bg-dark text-white" id="first_name" name="first_name" placeholder="Nombre" value="{{ user.first_name }}">
                    <label for="first_name" class="text-warning">Nombre:</label>
                </div>
                <div class="form-floating mb-3">
                    <input type="text" class="form-control bg-dark text-white" id="last_name" name="last_name" placeholder="Apellido" value="{{ user.last_name }}">
                    <label for="last_name" class="text-warning">Apellido:</label>
                </div>
                <div class="form-floating mb-3">
                    <input type="text" class="form-control bg-dark text-white" id="email" name="email" placeholder="Email" value="{{ user.email }}">
                    <label for="email" class="text-warning">Email:</label>
                </div>
                <div class="mt-3 d-flex">
                    <button class="btn btn-outline-warning m-auto">Guardar cambios</button>
                </div>
            </div>
        </form>
    </div>
</section>
{% endblock PAGE_CONTENT %}
{% block PAGE_SCRIPT %}
    <script>
        $(document).ready(function() {
            $('#inputFile').change(function() {
              var input = this;
          
              if (input.files && input.files[0]) {
                var reader = new FileReader();
          
                reader.onload = function(e) {
                  $('#user-avatar').attr('src', e.target.result);
                };
          
                reader.readAsDataURL(input.files[0]);
              }
            });
        });
    </script>
{% endblock PAGE_SCRIPT %}

apps/blog/templates/blog/index.html
{% extends 'base_blog.html' %}
{% block PAGE_TITLE %} Home {% endblock PAGE_TITLE %}
{% block PAGE_CONTENT %}
    <div class="container mt-5 col-md-10 text-white w-100" style="padding-left: 30%; padding-top: 60px;">
        {% if message.error %}
            <div class="alert alert-danger w-50 d-flex ps-3 pe-3 pt-3 pb-3" role="alert">
                {{ message.error }}
            </div>
        {% endif %}
        {% if message.success %}
            <div class="alert alert-success w-50 d-flex ps-3 pe-3 pt-3 pb-3" role="alert">
                {{ message.success }}
            </div>
        {% endif %}
        <div class="w-50 d-flex ps-3 pe-3 bg-dark pt-3 pb-3 rounded">
            <span class="bg-dark text-warning fs-3 me-2">🤔</span>
            <input type="text" class="form-control bg-dark text-white rounded-pill ps-4" placeholder="Publicar" id="publicar"/>
        </div>
        {% if post_list %}
            {% for post in post_list %}
                <div class="card w-50 d-flex flex-column ps-3 pe-3 bg-dark pt-3 pb-3 mt-4">
                    <a href="{% url 'blog:post' %}?id={{ post.id }}" class="text-decoration-none text-white"><h3 class="card-title">{{ post.title }}</h3></a>
                    <p class="card-text text-warning">
                        {{ post.content }}
                    </p>
                    {% if post.image %}
                        <img class="card-img-bottom mx-auto" src="{{ post.image.url }}" style="max-height: 400px; width: fit-content; max-width: 100%;">
                    {% endif %}
                    <small class="ms-auto mt-3">{{ post.author.username }} - {{ post.publish_date|date:"d/m/Y H:i A" }}</small>
                    <div class="d-flex justify-content-end mt-3">
                        <a href="{% url 'blog:like_post' %}?id={{ post.id }}">
                            <button class="btn {% if post.vote %} btn-danger {% else %} btn-outline-light {% endif %} mx-2 my-auto p-2 border-0 shadow-sm">
                                {{ post.votes }} Me gusta 
                                <i class="{% if post.vote %} fa-solid {% else %} fa-regular {% endif %} fa-heart"></i>
                            </button>
                        </a>
                        <a href="{% url 'blog:post' %}?id={{ post.id }}">
                            <button class="btn btn-outline-light mx-2 my-auto p-2 border-0 shadow-sm">{{ post.commets }} comentarios</button>
                        </a>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>
{% endblock PAGE_CONTENT %}
{% block PAGE_SCRIPT %}
    <script>
        $('#publicar').click(function() {
            {% if user.is_authenticated %}
                window.location.href = 'submit'
            {% else %}
                $('#exampleModal').modal('show')
            {% endif %}
        })
    </script>
{% endblock PAGE_SCRIPT %}

apps/blog/templates/blog/post_detail.html
{% extends 'base_blog.html' %}
{% load static %}
{% block PAGE_TITLE %} Post {% endblock PAGE_TITLE %}
{% block PAGE_CONTENT %}
    <div class="container mt-5 col-md-10 text-white w-100" style="padding-left: 30%; padding-top: 60px;">
        <div class="card w-50 d-flex flex-column ps-3 pe-3 bg-dark pt-3 pb-3 mt-4">
            <h3 class="card-title">{{ post.title }}</h3>
            <p class="card-text text-warning">
                {{ post.content }}
            </p>
            {% if post.image %}
                <img class="card-img-bottom mt-3" src="{{ post.image.url }}" class="my-auto">
            {% endif %}
            <small class="ms-auto mt-3">{{ post.author.username }} - {{ post.publish_date|date:"d/m/Y H:i A" }}</small>
            <div class="w-100 d-flex justify-content-end mt-3">
                <a href="{% url 'blog:like_post' %}?id={{ post.id }}">
                    <button class="btn {% if post.vote %} btn-danger {% else %} btn-outline-light {% endif %} mx-2 my-auto p-2 border-0 shadow-sm">
                        {{ post.votes|length }} Me gusta 
                        <i class="{% if post.vote %} fa-solid {% else %} fa-regular {% endif %} fa-heart"></i>
                    </button>
                </a>
            </div>
            {% if post.author == user %}
                <a href="{% url 'blog:delete_post' %}?id={{ post.id }}">
                    <button class="btn btn-outline-danger mt-3">
                        <i class="fa-solid fa-trash"></i>
                        Eliminar publicación
                    </button>
                </a>
            {% endif %}
        </div>
    </div>
    <section class="mt-4 text-white" style="padding-left: 30%;">
        <h4 class="border-bottom w-50 pb-3">{{ post.commets }} Comentarios</h4>
        <form method="POST" class="w-50" action="{% url 'blog:comment_post' %}">
            {% csrf_token %}
            <div class="input-group w-100 bg-dark"> 
                <input type="text" hidden value="{{ post.id }}" name="post">
                <textarea 
                    class="form-control w-100 rounded-0 px-3 m-0 bg-dark text-white"
                    aria-label="Describe lo que quieres decir" 
                    placeholder="Texto"
                    style="resize: none; height: 100px;"
                    name="content"
                    required></textarea>
            </div>
            <div class="w-100 mt-2 d-flex justify-content-end">
                <button class="btn btn-warning rounded-pill" type="submit">Comentar</button>
            </div>
        </form>
    </section>
    <section class="mt-4 text-white" style="padding-left: 30%;">
        {% for comment in comments %}
            <div class="d-flex w-50 border border-white py-4 border-start-0 border-end-0">
                <div class="d-flex flex-column me-3">
                    {% if comment.author.avatar %}
                        <img src="{{ comment.author.avatar.url }}" alt="Avatar" class="mx-auto my-auto rounded-circle" style="height: 40px; width: 40px;" />
                    {% else %}
                        <img src="{% static 'base_profile.png' %}" alt="Avatar" class="mx-auto my-auto rounded-circle" style="height: 40px; width: 40px;">   
                    {% endif %}
                    <small class="text-white">{{ comment.author.username }}</small>
                </div>
                <div class="d-flex w-100 flex-column">
                    <div class="w-100 bg-dark text-warning p-3 rounded">{{ comment.content }}</div>
                    <div class="d-flex mt-3">
                        <small class="text-white ms-auto my-auto">{{ comment.publish_date|date:"d/m/y H:ia" }}</small>
                        {% if post.author == user or comment.author == user %}
                            <a href="{% url 'blog:delete_comment' %}?id={{ comment.id }}">
                                <button class="btn btn-outline-danger my-auto ms-2">
                                    <i class="fa-solid fa-trash"></i>
                                    Eliminar comentario
                                </button>
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </section>
{% endblock PAGE_CONTENT %}

apps/blog/templates/blog/profile.html
{% extends 'base_blog.html' %}
{% load static %}
{% block PAGE_TITLE %} Profile {% endblock PAGE_TITLE %}
{% block PAGE_CONTENT %}
<section class="container mt-5 col-md-10 text-white w-100" style="padding-left: 30%; padding-top: 60px;">
    <div class="card w-75 d-flex flex-column ps-3 pe-3 bg-dark pt-3 pb-3 mt-4">
        <h3>Información del perfil</h3>
        <div class="d-flex">
            <div class="mt-5 ms-3">
                <img 
                    src="{% if user.avatar %} {{ user.avatar.url }} {% else %} {% static 'base_profile.png' %} {% endif %}" 
                    alt="" 
                    width="250" 
                    height="250" 
                    class="rounded-circle">
            </div>
            <div class="d-flex flex-column w-100 ps-5">
                <a href="{% url 'blog:edit_profile' %}" class="ms-auto">
                    Editar perfil 
                    <i class="fa-solid fa-pen-to-square"></i>
                </a>
                <div class="d-flex mt-5 pt-2">
                    <strong class="text-warning">Nombre de usuario:</strong>
                    <span class="ms-3">{{ user.username }}</span>
                </div>
                <div class="d-flex mt-2">
                    <strong class="text-warning">Nombre:</strong>
                    <span class="ms-3">{{ user.first_name }} {{ user.last_name }}</span>
                </div>
                <div class="d-flex mt-2">
                    <strong class="text-warning">Email:</strong>
                    <span class="ms-3">{{ user.email }}</span>
                </div>
                <div class="d-flex mt-2">
                    <strong class="text-warning">Fecha creación:</strong>
                    <span class="ms-3">{{ user.date_joined|date:"d/m/Y H:i A" }}</span>
                </div>
                <div class="d-flex mt-2">
                    <strong class="text-warning">Ultimo login:</strong>
                    <span class="ms-3">{{ user.last_login|date:"d/m/Y H:i A" }}</span>
                </div>
            </div>
        </div>
        <div class="d-flex mt-5">
            <table class="table text-white text-center">
                <thead>
                    <tr>
                        <td>Cantidad de publicaciones:</td>
                        <td>Cantidad de intereacciones:</td>
                    </tr>
                </thead>
                <tbody class="fs-1">
                    <tr>
                        <td>{{ post_count|default:0}}</td>
                        <td>{{ likes_count|default:0}}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</section>
{% endblock PAGE_CONTENT %}