apps/blog/urls.py
from django.urls import path
from blog import views
from django.contrib.auth.views import LogoutView

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('submit', views.submit, name='submit'),
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', LogoutView.as_view(next_page='/'), name='logout'),
    path('post', views.post_detail, name='post'),
    path('like_post', views.like_post, name='like_post'),
    path('comment_post', views.comment_post, name='comment_post'),
    path('delete_comment', views.delete_comment, name='delete_comment'),
    path('delete_post', views.delete_post, name='delete_post'),
    path('profile', views.profile, name='profile'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
    path('about', views.about, name='about'),
    path('<str:undefined_url>', views.index, name='undefined_url'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('blog.urls', 'blog')),
    path('admin/', admin.site.urls),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base_blog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Blog | {% block PAGE_TITLE %}{% endblock PAGE_TITLE %}</title>
    <link rel="shortcut icon" href="{% static 'blogger.png' %}">
    <script src="https://kit.fontawesome.com/8b42d3490b.js" crossorigin="anonymous"></script>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body class="pb-5" style="background-color: #000">
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark border border-secondary border-start-0 border-top-0 border-end-0" style="background-color: #1A1A1B">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">
            <img src="{% static 'blogger.png' %}" width="50">
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <form class="d-flex m-auto w-50" action="{% url 'blog:index' %}">
              <input class="form-control me-2 bg-dark text-white w-100" type="search" name="search" placeholder="Buscar en blog" aria-label="Search">
            </form>
            <div class="d-flex">
                {% if user.is_authenticated %}
                  {% if user.is_staff %}
                    <div class="d-flex">
                      <small class="my-auto me-4 text-warning fst-italic">
                        <a href="/admin" class="text-decoration-none text-warning">
                          Administración
                        </a>
                      </small>
                    </div>
                  {% endif %}
                  {% if user.avatar %}
                    <a href="{% url 'blog:profile' %}" class="text-decoration-none me-2 my-auto">
                      <img src="{{ user.avatar.url }}" alt="Avatar" class="rounded-circle" style="height: 40px; width: 40px;" /> 
                    </a>
                  {% else %}
                    <a href="{% url 'blog:profile' %}" class="text-decoration-none me-2 my-auto">
                      <img src="{% static 'base_profile.png' %}" class="rounded-circle" style="height: 40px;">
                    </a>
                  {% endif %}
                  <div class="d-block">
                    <div class="d-inline-flex fs-5">
                      <a href="{% url 'blog:profile' %}" class="text-decoration-none">
                        <span class="text-warning">Bienvenido,</span>
                        <strong class="text-warning ms-1">{{ user.first_name }}</strong>
                      </a>
                    </div>
                    <div class="d-flex justify-content-end">
                      <a href="{% url 'blog:logout' %}" class="text-decoration-none">
                        <i class="text-warning">(Cerrar sesión)</i>
                      </a>
                    </div>
                  </div>
                {% else %}
                  <button type="button" class="btn btn-outline-warning" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    <span class="fa-solid fa-right-to-bracket me-2"></span>
                    Iniciar sesión
                  </button>
                {% endif %}
            </div>
          </div>
        </div>
    </nav>
    <div class="row w-100">
        <div class="col-md-2 ps-4 text-white vh-100 position-fixed d-flex flex-column" style="background-color: #1A1A1B; padding-top: 90px;">
          <h5 class="border-bottom pb-3">Ultimas publicaciones</h3>
          <ul class="list-group list-group-flush">
            {% for post in top_post %}
              <li class="list-group-item my-2 text-white" style="background-color: #1A1A1B;">
                <a href="{% url 'blog:post' %}?id={{ post.id }}" class="text-decoration-none text-warning">{{ post.title }}</a>
              </li>
            {% endfor %}
          </ul>
          <a href="{% url 'blog:about' %}" class="mt-auto mb-4 ms-auto text-warning">Sobre mí</a>
          {% comment %} <h5 class="border-bottom pb-3 mt-5">Grupos destacados</h3>
          <ul class="list-group list-group-flush">
            {% for group in top_groups %}
              <li class="list-group-item my-2 text-white" style="background-color: #1A1A1B;">
                <a href="{% url 'blog:post' %}?id={{ group.id }}" class="text-decoration-none text-warning">{{ group.title }}</a>
              </li>
            {% endfor %}
          </ul> {% endcomment %}
        </div>
        {% block PAGE_CONTENT %}
        {% endblock PAGE_CONTENT %}
    </div>
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Inicio de sesión</h1>
          </div>
          <div class="modal-body px-5">
            <form class="d-flex flex-column justify-content-center" method="POST" id="login-form" action="{% url 'blog:login' %}">
              {% csrf_token %}
              {{ form.as_p }}
              <div class="mb-3 w-75 mx-auto form-floating">
                <input type="text" class="form-control" id="inputEmailLogin" aria-describedby="emailHelp" placeholder="Nombre de usuario" name="username">
                <label for="inputEmailLogin">Nombre de usuario</label>
              </div>
              <div class="mb-3 w-75 mx-auto form-floating">
                <input type="password" class="form-control" id="inputPasswordLogin" placeholder="Contraseña" name="password">
                <label for="inputPasswordLogin">Contraseña</label>
              </div>
              <button type="submit" class="btn btn-warning rounded-pill w-50 mx-auto">Iniciar sesión</button>
            </form>
            <div class="mt-4 pt-2 d-flex border border-end-0 border-start-0 border-bottom-0">
              <span class="mx-auto">¿Aún no tienes cuenta? <a href="/register">Registrate aquí</a></span>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="{% static 'js/jquery-3.7.0.min.js' %}"></script>
    {% block PAGE_SCRIPT %}
    {% endblock PAGE_SCRIPT %}
</body>
</html>